Repository boostcampwm-2022/web16-Codocs, pull requests merged in 2022-12, with the labels that each got.

#43 fix: 사파리 크로스 브라우징 이슈 해결
  frontend/src/components/Editor.tsx
Labels: bug, 🎨 프론트엔드

#45 배열 기반 CRDT 알고리즘 구현
  .github/workflows/lighthouse.yaml
  backend/socket/crdt-linear-server/char.ts
  backend/socket/crdt-linear-server/crdt.ts
  backend/socket/index.ts
  backend/socket/package-lock.json
  backend/socket/package.json
  backend/socket/src/index.ts
  backend/socket/tsconfig.json
  backend/socket/types/crdt.d.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/@types/.gitkeep
  frontend/src/App.test.tsx
  frontend/src/components/.gitkeep
  frontend/src/components/Editor.tsx
  frontend/src/core/crdt-linear/char.ts
  frontend/src/core/crdt-linear/crdt.test.ts
  frontend/src/core/crdt-linear/crdt.ts
  frontend/src/core/sockets/sockets.ts
  frontend/src/pages/.gitkeep
  frontend/src/types/crdt.d.ts
Labels: 🎨 프론트엔드, 🌍백엔드

#50 마크다운 프리뷰 기능 추가 및 의존성 변경, normalize css로 교체
  frontend/package-lock.json
  frontend/package.json
  frontend/src/GlobalStyles.ts
  frontend/src/components/Editor.tsx
Labels: bug, 🎨 프론트엔드

#54 배열 기반 CRDT 구조 실행 시간 벤치마크 테스트 스크립트 작성
  .DS_Store
  benchmark/.gitignore
  benchmark/crdt-array/crdt/char.ts
  benchmark/crdt-array/crdt/crdt.ts
  benchmark/crdt-array/localDeleteTest.ts
  benchmark/crdt-array/localInsertRangeTest.ts
  benchmark/crdt-array/localInsertTest.ts
  benchmark/crdt-array/main.ts
  benchmark/crdt-array/remoteDeleteRangeTest.ts
  benchmark/crdt-array/remoteDeleteTest.ts
  benchmark/crdt-array/remoteInsertRangeTest.ts
  benchmark/crdt-array/remoteInsertTest.ts
  benchmark/package-lock.json
  benchmark/package.json
  benchmark/tsconfig.json
Labels: 🪑 벤치마크

#61 깃허브 OAuth 로그인, JWT 인가
  backend/api/package-lock.json
  backend/api/package.json
  backend/api/src/app.module.ts
  backend/api/src/auth/auth.controller.ts
  backend/api/src/auth/auth.module.ts
  backend/api/src/auth/auth.service.ts
  backend/api/src/auth/github.strategy.ts
  backend/api/src/auth/jwt-auth.guard.ts
  backend/api/src/auth/jwt.strategy.ts
  backend/api/src/auth/local.strategy.ts
  backend/api/src/main.ts
  backend/api/src/user/dto/user-create.dto.ts
  backend/api/src/user/dto/user-response.dto.ts
  backend/api/src/user/user.controller.ts
  backend/api/src/user/user.module.ts
  backend/api/src/user/user.service.ts
Labels: 🌍백엔드

#44 문서 페이지 레이아웃 및 SVG 아이콘용 컴포넌트 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/public/mockServiceWorker.js
  frontend/src/Router.tsx
  frontend/src/components/docList/DocList.test.tsx
  frontend/src/components/docList/DocList.tsx
  frontend/src/components/docList/index.ts
  frontend/src/components/docListContainer/DocListContainer.tsx
  frontend/src/components/docListContainer/index.ts
  frontend/src/components/docListItem/DocListItem.tsx
  frontend/src/components/iconButton/IconButton.tsx
  frontend/src/components/iconButton/index.ts
  frontend/src/components/sideBar/SideBar.tsx
  frontend/src/index.tsx
  frontend/src/mocks/handler.ts
  frontend/src/mocks/server.ts
  frontend/src/mocks/worker.ts
  frontend/src/pages/MainPage.tsx
  frontend/src/setupTests.ts
  frontend/src/types/document.d.ts
  frontend/src/utils/fetchBeforeRender.ts
Labels: 리뷰요청, 🎨 프론트엔드

#63 랜딩 페이지 레이아웃 추가
  frontend/src/assets/background-1.svg
  frontend/src/assets/background-2.svg
  frontend/src/assets/logo.svg
  frontend/src/pages/LandingPage.tsx
Labels: 🎨 프론트엔드

#68 CRDT 링크드 리스트 구조에서 벤치마크 테스트
  backend/socket/crdt-linear-ll/char.ts
  backend/socket/crdt-linear-ll/crdt.ts
  backend/socket/index.ts
  benchmark/.gitignore
  benchmark/crdt-WOOT/crdt/char.ts
  benchmark/crdt-WOOT/crdt/crdt.ts
  benchmark/crdt-WOOT/localDeleteTest.ts
  benchmark/crdt-WOOT/localInsertRangeTest.ts
  benchmark/crdt-WOOT/localInsertTest.ts
  benchmark/crdt-WOOT/main.ts
  benchmark/crdt-WOOT/remoteDeleteRangeTest.ts
  benchmark/crdt-WOOT/remoteDeleteTest.ts
  benchmark/crdt-WOOT/remoteInsertRangeTest.ts
  benchmark/crdt-WOOT/remoteInsertTest.ts
  benchmark/package.json
  benchmark/tsconfig.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/GlobalStyles.ts
  frontend/src/components/Editor.tsx
  frontend/src/core/crdt-linear-ll/char.ts
  frontend/src/core/crdt-linear-ll/crdt.test.ts
  frontend/src/core/crdt-linear-ll/crdt.ts
  frontend/src/core/crdt-linear/crdt.ts
  frontend/src/hooks/useDebounce.ts
Labels: 🪑 벤치마크

#70 Github 로그인 구현
  frontend/.template.env
  frontend/src/assets/github.svg
  frontend/src/components/loginButton/LoginButton.tsx
  frontend/src/components/loginButton/index.ts
  frontend/src/pages/LandingPage.tsx
  frontend/src/pages/MainPage.tsx
Labels: 🎨 프론트엔드

#71 React lazy 적용
  frontend/src/Router.tsx
Labels: 리뷰요청, 🎨 프론트엔드

#74 fallback UI 로 사용할 Spinner 컴포넌트 구현
  frontend/src/components/docListContainer/DocListContainer.tsx
  frontend/src/components/spinner/Spinner.tsx
  frontend/src/components/spinner/index.ts
Labels: 리뷰요청, 🎨 프론트엔드

#75 MSW Mocking 으로 프로필 / 문서 API 작업
  frontend/src/components/docListContainer/DocListContainer.tsx
  frontend/src/mocks/dummy/docList.ts
  frontend/src/mocks/dummy/document.ts
  frontend/src/mocks/dummy/userProfile.ts
  frontend/src/mocks/handler.ts
  frontend/src/types/userProfile.d.ts
Labels: 리뷰요청, 🎨 프론트엔드

#77 새로운 문서를 생성하는 버튼
  frontend/src/pages/MainPage.tsx
Labels: 리뷰요청, 🎨 프론트엔드

#80 Header 중앙에 페이지 제목 표시 및 Outlet 적용
  frontend/src/Router.tsx
  frontend/src/components/header/Header.tsx
  frontend/src/hooks/usePageName.ts
  frontend/src/pages/MainLayout.tsx
  frontend/src/pages/MainPage.tsx
Labels: 리뷰요청, 🎨 프론트엔드

#83 알림을 표시하는 Toast UI 구현
  frontend/src/Router.tsx
  frontend/src/atoms/toastMsgAtom.ts
  frontend/src/components/toastMsg/ToastMsg.tsx
  frontend/src/components/toastMsg/index.ts
Labels: 리뷰요청, 🎨 프론트엔드

#84 CRDT 구조 개선
  backend/socket/crdt-linear-ll/char.ts
  backend/socket/crdt-linear-ll/crdt.ts
  backend/socket/index.ts
  frontend/src/components/Editor.tsx
  frontend/src/core/crdt-linear-ll/char.ts
  frontend/src/core/crdt-linear-ll/crdt.test.ts
  frontend/src/core/crdt-linear-ll/crdt.ts
  frontend/src/core/crdt-linear/crdt.ts
  frontend/src/hooks/useDebounce.ts
Labels: 🎨 프론트엔드, 🌍백엔드

#88 Dropdown 컴포넌트 및 DropdownOption 컴포넌트 구현
  frontend/src/assets/angle-down.svg
  frontend/src/components/dropdown/Dropdown.tsx
  frontend/src/components/dropdown/index.ts
  frontend/src/components/dropdownOption/DropdownOption.tsx
  frontend/src/components/dropdownOption/index.ts
Labels: 리뷰요청, 🎨 프론트엔드

#89 기능 결합, 자동 저장, 제목 수정 기능 추가
  backend/api/src/auth/auth.controller.ts
  backend/api/src/auth/auth.service.ts
  backend/api/src/auth/github.strategy.ts
  backend/api/src/auth/jwt.strategy.ts
  backend/api/src/auth/local.strategy.ts
  backend/api/src/document/document.controller.spec.ts
  backend/api/src/document/document.controller.ts
  backend/api/src/document/document.entity.ts
  backend/api/src/document/document.service.ts
  backend/api/src/document/dto/document-create.dto.ts
  backend/api/src/document/dto/document-response.dto.ts
  backend/api/src/main.ts
  backend/api/src/user/dto/user-create.dto.ts
  backend/api/src/user/dto/user-response.dto.ts
  backend/api/src/user/dto/user-update.dto.ts
  backend/api/src/user/user.controller.ts
  backend/api/src/user/user.entity.ts
  backend/api/src/user/user.service.ts
  backend/api/src/userdocument/dto/userdocument-response.dto.ts
  backend/api/src/userdocument/userdocument.controller.ts
  backend/api/src/userdocument/userdocument.service.ts
  backend/socket/index.ts
  backend/socket/package-lock.json
  backend/socket/package.json
  frontend/.eslintrc.json
  frontend/src/Router.tsx
  frontend/src/components/Editor.tsx
  frontend/src/components/docList/DocList.tsx
  frontend/src/components/docListContainer/DocListContainer.tsx
  frontend/src/components/docListItem/DocListItem.tsx
  frontend/src/components/editorHeader/EditorHeader.tsx
  frontend/src/components/siteLogo/SiteLogo.tsx
  frontend/src/components/toastMsg/ToastMsg.tsx
  frontend/src/hooks/useTitle.ts
  frontend/src/hooks/useToast.ts
  frontend/src/index.tsx
  frontend/src/mocks/dummy/docList.ts
  frontend/src/pages/DocumentPage.tsx
  frontend/src/pages/LandingPage.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/types/document.d.ts
  frontend/src/utils/fetchBeforeRender.ts
  frontend/src/utils/utils.ts
Labels: 🎨 프론트엔드, 🌍백엔드

#95 404 페이지 구현
  frontend/src/Router.tsx
  frontend/src/assets/404.svg
  frontend/src/pages/NotFoundPage.tsx
Labels: 🎨 프론트엔드

#92 Feature/react query
  frontend/.template.env
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/GlobalStyles.ts
  frontend/src/Router.tsx
  frontend/src/assets/check.svg
  frontend/src/assets/exclamation.svg
  frontend/src/components/docList/DocList.tsx
  frontend/src/components/docListContainer/DocListContainer.tsx
  frontend/src/components/docListContainer/index.ts
  frontend/src/components/docListItem/DocListItem.tsx
  frontend/src/components/dropdown/Dropdown.tsx
  frontend/src/components/dropdownOption/DropdownOption.tsx
  frontend/src/components/editorHeader/EditorHeader.tsx
  frontend/src/components/header/Header.tsx
  frontend/src/components/iconButton/IconButton.tsx
  frontend/src/components/spinner/Spinner.tsx
  frontend/src/components/toastMsg/ToastMsg.tsx
  frontend/src/components/userProfile/UserProfile.tsx
  frontend/src/index.tsx
  frontend/src/mocks/dummy/charMap.ts
  frontend/src/mocks/dummy/docList.ts
  frontend/src/mocks/dummy/document.ts
  frontend/src/mocks/handler.ts
  frontend/src/pages/DocumentPage.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/PrivatePage.tsx
  frontend/src/pages/SharedPage.tsx
  frontend/src/types/document.d.ts
  frontend/src/utils/fetchBeforeRender.ts
Labels: 리뷰요청, 🎨 프론트엔드

#93 Modal 컴포넌트 구현
  frontend/src/Router.tsx
  frontend/src/atoms/modalAtom.ts
  frontend/src/components/modal/Modal.tsx
  frontend/src/components/modal/index.ts
Labels: 리뷰요청, 🎨 프론트엔드

#96 DocListItem 버튼에 API 호출 함수 및 Modal 실행 함수 전달
  frontend/src/atoms/modalAtom.ts
  frontend/src/components/docList/DocList.tsx
  frontend/src/components/docListItem/DocListItem.tsx
  frontend/src/components/modal/Modal.tsx
  frontend/src/components/modalDoubleChecker/ModalDoubleChecker.tsx
  frontend/src/components/modalDoubleChecker/index.ts
  frontend/src/mocks/dummy/docList.ts
  frontend/src/mocks/handler.ts
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/PrivatePage.tsx
  frontend/src/pages/SharedPage.tsx
  frontend/src/types/document.d.ts
Labels: 리뷰요청, 🎨 프론트엔드

#98 feat: Private, Shared 문서 목록 API
  backend/api/package-lock.json
  backend/api/package.json
  backend/api/src/document/document.service.ts
  backend/api/src/enum/role.enum.ts
  backend/api/src/userdocument/dto/userdocument-create.dto.ts
  backend/api/src/userdocument/dto/userdocument-response.dto.ts
  backend/api/src/userdocument/dto/userdocument-update.dto.ts
  backend/api/src/userdocument/userdocument.controller.ts
  backend/api/src/userdocument/userdocument.entity.ts
  backend/api/src/userdocument/userdocument.service.ts
Labels: 리뷰요청, 🌍백엔드

#101 에디터에 접속 중인 인원을 표시하는 OnlinePeople 컴포넌트 구현
  frontend/src/assets/online.svg
  frontend/src/components/editorHeader/EditorHeader.tsx
  frontend/src/components/onlinePeople/OnlinePeople.tsx
  frontend/src/components/onlinePeople/index.ts
Labels: 리뷰요청, 🎨 프론트엔드

#102 공유커서 기능 구현
  backend/socket/index.ts
  frontend/src/atoms/profileAtom.ts
  frontend/src/components/Editor.tsx
  frontend/src/core/cursor/cursor.ts
  frontend/src/hooks/useProfile.ts
  frontend/src/utils/utils.ts
Labels: 🎨 프론트엔드, 🌍백엔드

#103 NestJS 글로벌 Exception 필터
  backend/api/src/document/document.service.ts
  backend/api/src/filters/all-exception.filter.ts
  backend/api/src/filters/http-exception.filter.ts
  backend/api/src/main.ts
Labels: 🌍백엔드
