Repository boostcampwm-2022/web16-Codocs, pull requests merged in 2022-11, with the labels that each got.

#18 styled components 글로벌 스타일 적용, 이미지 에셋 추가, CSS 필터 및 색상 상수화
  .github/workflows/CLIENT_CI.yml
  frontend/public/index.html
  frontend/src/App.test.tsx
  frontend/src/App.tsx
  frontend/src/GlobalStyles.ts
  frontend/src/assets/bookmark.svg
  frontend/src/assets/house.svg
  frontend/src/assets/lock.svg
  frontend/src/assets/pencil.svg
  frontend/src/assets/refly.svg
  frontend/src/assets/together.svg
  frontend/src/assets/trash.svg
  frontend/src/assets/trashbag.svg
  frontend/src/constants/styled.ts
  frontend/src/index.tsx
Labels: 리뷰요청, 🎨 프론트엔드

#17 feat: #6 lighthouse 커스텀 액션 적용
  .github/workflows/lighthouse.yaml
Labels: ⚙️ 환경설정

#21 개별 문서 아이템 컴포넌트 구현 및 클릭 시 라우팅 구현
  frontend/src/components/docListItem/DocListItem.tsx
  frontend/src/components/docListItem/index.ts
  frontend/src/pages/MainPage.tsx
Labels: 🎨 프론트엔드

#26 사이드바 컴포넌트 구현
  .DS_Store
  frontend/src/assets/bookmark.svg
  frontend/src/assets/house.svg
  frontend/src/assets/lock.svg
  frontend/src/assets/pencil.svg
  frontend/src/assets/refly.svg
  frontend/src/assets/together.svg
  frontend/src/assets/trash.svg
  frontend/src/assets/trashbag.svg
  frontend/src/components/sideBar/SideBar.tsx
  frontend/src/components/sideBar/index.ts
Labels: 🎨 프론트엔드

#28 에디터 장착
  frontend/package-lock.json
  frontend/package.json
  frontend/src/@types/.gitkeep
  frontend/src/App.tsx
  frontend/src/Router.tsx
  frontend/src/components/.gitkeep
  frontend/src/components/Editor.tsx
  frontend/src/hooks/.gitkeep
  frontend/src/pages/.gitkeep
  frontend/src/pages/DocumentPage.tsx
  frontend/src/pages/LandingPage.tsx
  frontend/src/utils/.gitkeep
Labels: 리뷰요청, 🎨 프론트엔드, 🚨 긴급

#27 CRUD API 개발, Swagger API 문서
  backend/api/package-lock.json
  backend/api/package.json
  backend/api/src/app.module.ts
  backend/api/src/bookmark/bookmark.controller.ts
  backend/api/src/bookmark/bookmark.entity.ts
  backend/api/src/bookmark/bookmark.service.ts
  backend/api/src/bookmark/dto/bookmark-create.dto.ts
  backend/api/src/bookmark/dto/bookmark-response.dto.ts
  backend/api/src/document/document.controller.spec.ts
  backend/api/src/document/document.controller.ts
  backend/api/src/document/document.entity.ts
  backend/api/src/document/document.service.ts
  backend/api/src/document/dto/document-create.dto.ts
  backend/api/src/document/dto/document-response.dto.ts
  backend/api/src/document/dto/document-update.dto.ts
  backend/api/src/main.ts
  backend/api/src/pipes/validation.pipe.ts
  backend/api/src/user/dto/user-create.dto.ts
  backend/api/src/user/dto/user-response.dto.ts
  backend/api/src/user/dto/user-update.dto.ts
  backend/api/src/user/user.controller.ts
  backend/api/src/user/user.entity.ts
  backend/api/src/user/user.service.ts
  backend/api/src/userdocument/dto/userdocument-create.dto.ts
  backend/api/src/userdocument/dto/userdocument-response.dto.ts
  backend/api/src/userdocument/dto/userdocument-update.dto.ts
  backend/api/src/userdocument/enum/role.enum.ts
  backend/api/src/userdocument/userdocument.controller.ts
  backend/api/src/userdocument/userdocument.entity.ts
  backend/api/src/userdocument/userdocument.module.ts
  backend/api/src/userdocument/userdocument.service.ts
Labels: 🌍백엔드

#35 소켓 서버에 문서 데이터 인메모리에 저장 / 불러오기 구현
  backend/socket/crdt-linear-server/char.ts
  backend/socket/crdt-linear-server/crdt.ts
  backend/socket/index.ts
  backend/socket/package-lock.json
  backend/socket/package.json
  backend/socket/src/index.ts
  backend/socket/tsconfig.json
  backend/socket/types/crdt.d.ts
  frontend/src/components/Editor.tsx
  frontend/src/core/crdt-linear/crdt.ts
Labels: 🎨 프론트엔드, 🌍백엔드

#37 siteId 비교 로직 추가
  frontend/src/core/crdt-linear/crdt.test.ts
  frontend/src/core/crdt-linear/crdt.ts
Labels: 🎨 프론트엔드
